---
title: "IM532 3.0 Applied Time Series Forecasting"
subtitle: "MSc in Industrial Mathematics"
author: "Dr. Thiyanga Talagala"
date: "8 March 2020"
output:
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js
    lib_dir: libs
    css: 
      - default
      - default-fonts
      - duke-blue
      - hygge-duke
      - libs/cc-fonts.css
      - libs/figure-captions.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# Hierarchical time series

- Forecasting time series that are hierarchical in structure

- Clusters of time sereis may be correlated.

---

# Notation for hierarchical forecasting

## Aggregated series and Disaggregated series

---
exclude: true

# Importance of modelling the entire hierarchy of time series simultaneously.

- The verious components of the hierarchy can interact in varying and complex ways. 

- A change in one series at one level, can have a consequential impact on oter series at the same level, as well as series at higher and lower levels. 

- Current forecasting methodology for hierarchical systems has not attempted to model this complex behaviour at all. By modelling the entire hierarchy of time series simultaneouly, we will obtain better forecasts of the component series. 

---

class: middleclass, duke-blue

# Approaches of Forecasting Hierarchical Time Series

1. top-down

2. bottom-up

3. combination of top-down and bottom-up (sometimes called "middle-out")


---

# Top-down approach

1. Forecasting the compeletely aggregated time series.

2. Disaggregating the forecasts based on historical proportions.

3. Different ways of choosing proportions (Gross and Sohl, 1990)

---

# Bottom-up approach

1. Forecasting each of the disaggregated series at the lowest level of the hierarchy.

2. Aggregate the time series.


---

# Middle-out approach


1. Forecast are obtained for each series at an intermediate level of the hierarchy.

2.  Then,

      - Aggregate - to obtain forecasts at higher levels.

      - Disaggregate - obtain forecasts at lower levels.


---

exclude: true


Of course, it is also possible to forecast all series at all levels independently, but this has the undesirable consequence of the higher level forecasts not being equal to the sum of the lower level forecasts. Consequently, if this method is used, some adjustment is then carried out to ensure the forecasts add upp appropriately.  These adjustments are usually done in an ad hoc manner.


- An early contribution was Grunfeld and Griliches (1960) who argued that the disaggregated data are arror-prone and that **top-down forecasts may therefore be more accurate**.

---

# Limitations 

- Does not take account of the inherent correlation structure of the hierarchy. 

- Does not take account of the covariance structure of the component series.

- Difficult to obtain prediction intervals.

---

# Notations

## Aggregate of all series at time t

$$Y_t=\sum_i Y_{i, t}$$



