---
title: "Introduction to linear time series models"
author:
- familyname: Thiyanga
  othernames: Talagala
  address: University of Sri Jayewardenepura
  email: ttalagala@sjp.ac.lk
  correspondingauthor: true
abstract: ""
keywords: ""
blind: false
cover: false
toc: true
bibliography: references.bib
biblio-style: authoryear-comp
output:
  MonashEBSTemplates::workingpaper:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, messages=FALSE, warning=FALSE)
# Make sure you have the latest version of rmarkdown and bookdown
#devtools::install_github("rstudio/rmarkdown")
#devtools::install_github("rstudio/bookdown")
library(ggplot2)
```


# Introduction

In a famous paper, @BC64 introduced a family of transformations \dots

```{r histogram, fig.cap="Nice histogram", message=FALSE, warning=FALSE}
qplot(exp(rnorm(200)))
```

Consider the logNormal data plotted in Figure \ref{fig:histogram}.

$$s^2 = \sum_{i=1}^n (x_i-\bar{x})^2$$

$$
\begin{aligned}
  \dot{x} & = \sigma(y-x) \\
  \dot{y} & = \rho x- y - xz 
\end{aligned}
$$

